### ISSUE TITLE
Debrief + Standup 16.03.20

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/handbook#3]
# Debrief

* End of an era moving back from SF!
* DAUs fairly flat through the week. If no increase by Wednesday from last week, then we will prioritise the sign up process. We think the lack fo increase is that although we're adding more deployments, that we've had gradual churn from the week before. 
*  Happy with throughput on development side. Prioritization is a little tough - typically 50% of each day is spent fixing random issues.

# Todo

## Tim
- [ ] @timgl to create a ticket to make Actions more intuitive
  - [ ] 'Filters' or 'Tags'?
  - [ ] There is already a ticket to add event filtering to the trends
  - [ ] Think how else to make this easier
  - [ ] The /Actions form is also confusing people
- [x] Send @Tannergoods a list of the PRs in 1.07 and 1.08 respectively

## James
- [ ] QA issues that you started
- [ ] Book the YC demo day stuff in as it comes through
- [ ] Establish new plan by Wednesday night depending on Mon-Weds progress
- [ ] If time, and on top of fundraise, get the forum setup / documentation migration done
## Aaron
- [x] QA 360 and 359
- [x] Feedback from sign ups over the weekend
- [x] Get the blog live
- [x] Schedule Slack/Tweets/Facebook/LinkedIn/Email
  - [x] Use MailChimp
- [x] Make videos.
  - [ ] Prioritize a "demo" video to help encourage people when they deploy to actually deploy to production
