### ISSUE TITLE
Debrief + Standup 23.03.20

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/handbook#4]
# Debrief

* Freelance spend a little high (15hrs/week, not 10). That's ok, don't let it get above 20.
* Sign ups are coming through organically. The number looks inflated but that's due to personal sign up then production sign up, which indicates quality.
* The Array newsletter had 40% open, 6% CTR which we are happy with for a start.
* DAUs not trending the right way yet.

# Todo

## James
- [x] Continue to focus on fundraising. A large chunk done.
- [ ] Write up a/b testing ticket.
- [ ] QA the DAUs once Marius PR is merged.

## Aaron
- [x] Work out some way of tracking the sign ups -> gone live
- [x] One more blog post live
- [ ] Get Twitter up and running
- [x] Update documentation w/ product changes last week
- [x] Get a demo done (focus on "what it does when up and running")

## Tim
- [ ] Making the setup better: create a ticket:
  - [ ] (i) to create a few more pre-populated actions and
  - [ ] (ii) a few more example users and
  - [ ] (iii) some way of deleting this
- [ ] Ruby task for Marius (for the GitLab app integration), depending on discussion today
