### ISSUE TITLE
Debrief + Standup 30.03.20

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/handbook#7]
# Debrief

* DAUs were better than previous week - out of the dip!
* We had a ~50% conversion rate sign ups -> actual users
* Good activity towards the end of the week - demo video, and anecdotal responses that people are reading the updates
* Happy with hiring progress, but want a bit more coverage.
* GitLab call over weekend was positive.

# Todo

## Tim
- [ ] Get YC to publish a job ad (bottlenecked: careers page needed)
- [ ] Get the first hire done
- [ ] Clarify Marius' workload
- [ ] Product: make actions fast

## Aaron
- [x] Get a careers page live
- [x] Create a shortlist of customers that could be references and speak to them
- [x] Videos for every other day
- [x] Tweet every day
- [x] Array needs to go out for Wednesday
- [ ] Get marketing for developers

## James
- [ ] Keep up 5-10 meetings/day
- [ ] Nail the later meetings with good seed funds
- [ ] Fundraising strategy revisit on Wednesday
- [ ] Push the docs site live to a subfolder
